apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetime-prod-api
  labels:
    app: treetime
    env: prod
    service: treetime-prod-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: treetime
      env: prod
      service: treetime-prod-api

  template:
    metadata:
      labels:
        app: treetime
        env: prod
        service: treetime-prod-api

    spec:
      containers:
        - name: treetime-prod-api
          image: treetime-prod-api
          imagePullPolicy: IfNotPresent
          env:
            - name: FILESTORE_HOST
              value: http://treetime-prod-filestore
            - name: FILESTORE_PORT
              value: '9000'
            - name: TASK_QUEUE_HOST
              value: amqp://treetime-prod-taskqueue
            - name: TASK_QUEUE_PORT
              value: '5672'
          resources:
            limits:
              cpu: '0.5'
              memory: '512Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: treetime-prod-api
  labels:
    app: treetime
    env: prod
    service: treetime-prod-api
spec:
  type: ClusterIP
  selector:
    app: treetime
    env: prod
    service: treetime-prod-api
  ports:
    - port: 5000
