apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetime-prod-reverseproxy
  labels:
    app: treetime
    env: prod
    service: treetime-prod-reverseproxy

spec:
  replicas: 1

  selector:
    matchLabels:
      app: treetime
      env: prod
      service: treetime-prod-reverseproxy

  template:
    metadata:
      labels:
        app: treetime
        env: prod
        service: treetime-prod-reverseproxy

    spec:
      containers:
        - name: treetime-prod-reverseproxy
          image: treetime-prod-reverseproxy
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '0.25'
              memory: '128Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: treetime-prod-reverseproxy
  labels:
    app: treetime
    env: prod
    service: treetime-prod-reverseproxy
spec:
  type: ClusterIP
  selector:
    app: treetime
    env: prod
    service: treetime-prod-reverseproxy
  ports:
    - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: treetime-prod-loadbalancer
  labels:
    app: treetime
    env: prod
    service: treetime-prod-reverseproxy

spec:
  type: LoadBalancer

  selector:
    app: treetime
    env: prod
    service: treetime-prod-reverseproxy

  ports:
    - port: 80
      targetPort: 80
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: treetime-prod-ingress
#   labels:
#     app: treetime
#     env: prod
#     service: treetime-prod-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               serviceName: treetime-prod-reverseproxy
#               servicePort: 80

