version: '3.7'

services:
  treetime-package-treetime:
    container_name: treetime-package-treetime
    image: treetime-package-treetime
    build:
      context: ./
      dockerfile: python3-git-ubuntu/Dockerfile
    command: sh -c "cd /code/treetime && pip3 --quiet install . && python3 setup.py sdist bdist_wheel"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
