version: '3.7'

services:
  treetime-dev-api:
    container_name: treetime-dev-api
    image: treetime-dev-api
    build:
      context: ./
      dockerfile: node-git-alpine/Dockerfile
    command: sh -c "cd /code/api && yarn install && yarn dev"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
