version: '3.7'

services:
  treetime-dev-worker:
    container_name: treetime-dev-worker
    image: treetime-dev-worker
    build:
      context: ../
      dockerfile: worker/Dockerfile
    command: sh -c "cd /code/worker && python3 src/main.py"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
