version: '3.7'

services:
  treetime-dev-reverseproxy:
    depends_on:
      - treetime-dev-api
      - treetime-dev-web
    container_name: treetime-dev-reverseproxy
    image: treetime-dev-reverseproxy
    build:
      context: ./
      dockerfile: ../services/reverseproxy/development/Dockerfile
    command: sh /etc/nginx/nginx-watch.sh
    volumes:
      - ../services/reverseproxy/development/etc/nginx:/etc/nginx:ro
      - ../.volumes/development/nginx/cache:/var/cache/nginx
      - ../.volumes/development/nginx/logs:/var/lib/nginx/logs
      - ../.volumes/development/nginx/tmp:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 44443:44443
      - 8080:8080
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    tty: true

  treetime-dev-api:
    depends_on:
      - treetime-dev-taskqueue
      - treetime-dev-filestore
    container_name: treetime-dev-api
    image: treetime-dev-api
    build:
      context: ./
      dockerfile: node-git-alpine/Dockerfile
    command:
      sh -c "cd /code/services/api && yarn install --silent --no-progress
      --non-interactive >/dev/null && dockerize -wait
      tcp://treetime-dev-taskqueue:5672 -timeout 60s >& /dev/null && yarn dev"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
      - TASK_QUEUE_HOST=amqp://treetime-dev-taskqueue
      - TASK_QUEUE_PORT=5672
      - FILESTORE_HOST=http://treetime-dev-filestore
      - FILESTORE_PORT=9000
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-web:
    depends_on:
      - treetime-dev-api
    container_name: treetime-dev-web
    image: treetime-dev-web
    build:
      context: ./
      dockerfile: node-git-alpine/Dockerfile
    command:
      sh -c "cd /code/services/web && cp .env.example .env && yarn install
      --silent --no-progress --non-interactive >/dev/null && yarn dev"
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-worker-base:
    container_name: treetime-dev-worker-base
    image: treetime-dev-worker-base
    build:
      context: ../
      dockerfile: services/worker/docker/development.dockerfile
    command:
      bash -c "cd /code/services/worker && yarn install --silent --no-progress
      --non-interactive >/dev/null && yarn dev:docker:base"
    volumes:
      - ../:/code
      - ../services/worker/docker/.config/pypoetry/config.toml:/.config/pypoetry/config.toml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-worker:
    depends_on:
      - treetime-dev-worker-base
      - treetime-dev-taskqueue
      - treetime-dev-filestore
    image: treetime-dev-worker
    build:
      context: ../
      dockerfile: services/worker/docker/development.dockerfile
    command: bash -c "yarn dev:docker:main"
    volumes:
      - ../:/code
      - ../services/worker/docker/.config/pypoetry/config.toml:/.config/pypoetry/config.toml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
      - API_HOST=treetime-dev-api
      - API_PORT=5000
      - FILESTORE_HOST=http://treetime-dev-filestore
      - FILESTORE_PORT=9000
      - TASK_QUEUE_HOST=treetime-dev-taskqueue
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
    deploy:
      replicas: 3

  treetime-dev-taskqueue:
    container_name: treetime-dev-taskqueue
    image: rabbitmq:3.8.2-management-alpine
    volumes:
      - ../:/code
      - ../.volumes/development/taskqueue/config/generated:/var/lib/rabbitmq/config/generated
      - ../services/taskqueue/dev/etc/rabbitmq:/etc/rabbitmq:ro
      - ../services/taskqueue/dev/var/lib/rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ../.env
    environment:
      - RABBITMQ_NODENAME=taskqueue001
      - RABBITMQ_HOME=/code/.volumes/development/taskqueue/home
      - RABBITMQ_MNESIA_BASE=/code/.volumes/development/taskqueue/mnesia
      - RABBITMQ_LOG_BASE=/code/.volumes/development/taskqueue/log
      - RABBITMQ_SCHEMA_DIR=/code/.volumes/development/taskqueue/schema
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true

  treetime-dev-filestore:
    container_name: treetime-dev-filestore
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    command: server --quiet /code/.volumes/development/filestore
    volumes:
      - ../:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000
    env_file:
      - ../.env
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-truecolor
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
