apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: treetime-prod-ingress
  labels:
    app: treetime
    env: prod
    service: treetime-prod-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: treetime-prod-web
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: treetime-prod-api
                port:
                  number: 5000
