apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetime-prod-web
  labels:
    app: treetime
    env: prod
    service: treetime-prod-web

spec:
  replicas: 1

  selector:
    matchLabels:
      app: treetime
      env: prod
      service: treetime-prod-web

  template:
    metadata:
      labels:
        app: treetime
        env: prod
        service: treetime-prod-web

    spec:
      containers:
        - name: treetime-prod-web
          image: treetime-prod-web
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '0.25'
              memory: '128Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: treetime-prod-web
  labels:
    app: treetime
    env: prod
    service: treetime-prod-web
spec:
  type: ClusterIP
  selector:
    app: treetime
    env: prod
    service: treetime-prod-web
  ports:
    - port: 80

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: loadbalancer
#   labels:
#     app: treetime
#     env: prod
#     service: treetime-prod-web

# spec:
#   type: LoadBalancer

#   selector:
#     app: treetime
#     env: prod
#     service: treetime-prod-web

#   ports:
#     - port: 80
#       targetPort: 80
