language: python
python:
  - "2.7"
# command to install dependencies
before_install:
    - sudo apt-get install -qq python-numpy python-scipy
install: "pip install biopython"
# command to run tests
script:
    - bash .travis_test.sh
