language: python
sudo: true
python:
  - "2.7"
# command to install dependencies
virtualenv:
  system_site_packages: true
install:
  - pip install .
# command to run tests
script:
    - bash .travis_test.sh
