language: python
sudo: true
python:
  - "3.5"
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-numpy python-scipy
install:
  - pip3 install nose
  - pip3 install biopython
  - python3 setup.py build
  - python3 setup.py install
# command to run tests
script:
  - bash .travis_test.sh
