sudo: false
language: python
python:
  - "2.7"
# command to install dependencies
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
install: "pip install -r requirements.txt"
# command to run tests
script:
    - bash .travis_test.sh
